import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { SessionProvider } from "./session-provider";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";
import { SiteHeader } from "@/components/site-header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Nim Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"></link>
      </head>
      <SessionProvider>
        <body
          className={inter.className}
        >
          <ThemeProvider>
            <div className="relative flex min-h-screen flex-col">
              <SiteHeader />
              {children}
            </div>
          </ThemeProvider>
        </body>
      </SessionProvider>
    </html>
  );
}
